name: Build and deploy to Azure Web App - CookLikeMe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    # Comment out Docker setup, login, build, and push
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Log in to registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: https://mcr.microsoft.com/
    #     username: ${{ secrets.AzureAppService_ContainerUsername_ce31e97a5f784853b8fab961c761246f }}
    #     password: ${{ secrets.AzureAppService_ContainerPassword_a43264823f9f4822843edd0b5d360b66 }}

    # - name: Build and push container image to registry
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ce31e97a5f784853b8fab961c761246f }}/appsvc/staticsite:${{ github.sha }}
    #     file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CookLikeMe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_df2e9068ce2843f5ac2065fe4f09c791 }}
        # If you're not using Docker, you may want to upload directly instead of using a container image
        # The `images` field is for Docker container images, so it can be removed or adjusted based on your app's build type.
